// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
var SERVICES = [
  {
    id: "str-turnover",
    name: "Short-term rental turnover",
    summary: "Between-guest reset for Airbnb/VRBO units: full clean, linen change, staging to listing photos, restock and damage reporting."
  },
  {
    id: "listing-prep",
    name: "Listing preparation",
    summary: "Deep reset before photography or relisting: detail clean, declutter, surface polish and photo-ready staging."
  },
  {
    id: "recurring-coverage",
    name: "Recurring coverage",
    summary: "Scheduled turnover coverage for operators with repeating bookings, including backup crew for same-day gaps."
  },
  {
    id: "move-out",
    name: "Move-out / vacancy cleans",
    summary: "Vacant unit resets for property managers and landlords between tenancies."
  },
  {
    id: "emergency",
    name: "Emergency / same-day turnover",
    summary: "Prioritised rush scheduling when a guest checks out late or a crew no-shows."
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List the property readiness and turnover services Niagara Turnover Co. offers, with a short summary of each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/list-service-areas.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
var AREAS = [
  { slug: "niagara-falls", name: "Niagara Falls", url: "/service-area/niagara-falls" },
  { slug: "st-catharines", name: "St. Catharines", url: "/service-area/st-catharines" },
  {
    slug: "niagara-on-the-lake",
    name: "Niagara-on-the-Lake",
    url: "/service-area/niagara-on-the-lake"
  },
  { slug: "welland", name: "Welland", url: "/service-area/welland" },
  { slug: "thorold", name: "Thorold", url: "/service-area/thorold" },
  { slug: "port-colborne", name: "Port Colborne", url: "/service-area/port-colborne" },
  { slug: "fort-erie", name: "Fort Erie", url: "/service-area/fort-erie" }
];
var list_service_areas_default = defineTool2({
  name: "list_service_areas",
  title: "List service areas",
  description: "List the Niagara Region cities Niagara Turnover Co. covers, with the slug and landing page path for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(AREAS, null, 2) }],
    structuredContent: { areas: AREAS }
  })
});

// src/lib/mcp/tools/estimate-turnover.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";
var BASE = 89;
var PER_BEDROOM = 32;
var PER_BATHROOM = 28;
var RUSH_MULTIPLIER = 1.35;
var LINEN_FEE = 25;
var estimate_turnover_default = defineTool3({
  name: "estimate_turnover",
  title: "Estimate a turnover",
  description: "Produce an indicative turnover price range for a Niagara property based on bedrooms, bathrooms, rush scheduling and linen service. Indicative only \u2014 final pricing depends on scope and condition.",
  inputSchema: {
    bedrooms: z.number().int().describe("Number of bedrooms (0 for studio)."),
    bathrooms: z.number().describe("Number of bathrooms, halves allowed."),
    rush: z.boolean().optional().describe("Same-day or emergency scheduling."),
    linen: z.boolean().optional().describe("Include linen supply and laundering.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ bedrooms, bathrooms, rush, linen }) => {
    const beds = Math.max(0, Math.min(12, Math.round(bedrooms)));
    const baths = Math.max(0, Math.min(12, bathrooms));
    let low = BASE + beds * PER_BEDROOM + baths * PER_BATHROOM;
    if (linen) low += LINEN_FEE;
    if (rush) low *= RUSH_MULTIPLIER;
    const high = low * 1.25;
    const result = {
      currency: "CAD",
      low: Math.round(low),
      high: Math.round(high),
      bedrooms: beds,
      bathrooms: baths,
      rush: Boolean(rush),
      linen: Boolean(linen),
      disclaimer: "Indicative range only. Final pricing depends on property scope, condition and access."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-booking-links.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
var CONTACT = {
  business: "Niagara Turnover Co.",
  phone: "(289) 257-7725",
  phoneE164: "+12892577725",
  website: "https://niagaraturnoverco.com",
  clientScheduling: "https://airtable.com/app3bo82kH3gBbh7D/pagam8AZIIRd6Xqew/form",
  clientOnboarding: "https://airtable.com/app3bo82kH3gBbh7D/pagfETpx8mh312gUE/form",
  region: "Niagara Region, Ontario, Canada"
};
var get_booking_links_default = defineTool4({
  name: "get_booking_links",
  title: "Get booking and contact links",
  description: "Return Niagara Turnover Co.'s phone number and the Client Scheduling and Client On-Boarding form links to send a property owner or operator to.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/tools/get-readiness-standard.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
var CHECKLIST = [
  "Kitchen: counters, appliances inside and out, sink polished, dishware verified and put away",
  "Bathrooms: descaled fixtures, mirrors streak-free, fresh towel set staged, consumables restocked",
  "Bedrooms: hotel-standard linen change, bed styled to listing photos, surfaces dusted",
  "Living areas: floors vacuumed and washed, cushions reset, remotes and cables tidied",
  "Staging: property reset to match the live listing photos before departure",
  "Reporting: damage, missing items and low stock photographed and reported same day"
];
var get_readiness_standard_default = defineTool5({
  name: "get_readiness_standard",
  title: "Get the readiness standard",
  description: "Return the room-by-room readiness checklist Niagara Turnover Co. applies to every turnover, plus the reporting commitment.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: CHECKLIST.map((line) => `- ${line}`).join("\n") }],
    structuredContent: { checklist: CHECKLIST }
  })
});

// src/lib/mcp/index.ts
var projectRef = "bjuuutvdqrupbbuckewj";
var mcp_default = defineMcp({
  name: "niagara-readiness-hub",
  title: "Niagara Readiness Hub",
  version: "0.1.0",
  instructions: "Tools for Niagara Turnover Co., a short-term rental and property turnover service in the Niagara Region of Ontario. Use `list_services` and `get_readiness_standard` to explain what is covered, `list_service_areas` for coverage, `estimate_turnover` for an indicative price range, and `get_booking_links` to hand the caller the scheduling or on-boarding form.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_services_default,
    list_service_areas_default,
    get_readiness_standard_default,
    estimate_turnover_default,
    get_booking_links_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
